added tests retry

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -29,8 +29,15 @@ jobs:
       - name: Lint
         run: npm run lint
 
+      - name: Create tests db
+        run: npx prisma migrate dev
+
       - name: Test
-        run: npm run test
+        run: |
+          (echo "===== Running tests Attempt: 1 ====" && npm run test) || \
+          (echo "===== Running tests Attempt: 2 ====" && npm run test) || \
+          (echo "===== Running tests Attempt: 3 ====" && npm run test) || \
+          (echo "==== Tests Step Failed ====" && exit 1)
 
       - name: Build
         run: npm run build
